# Generated by Django 5.0.4 on 2024-04-18 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
    ]
