# Generated by Django 5.0.4 on 2024-05-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telefone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
