# Generated by Django 5.0.3 on 2024-03-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_agendamento_data_entrega_prevista'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='nova_data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
