# Generated by Django 4.2.3 on 2024-02-20 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_alter_usuario_data_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nome',
        ),
    ]
