# Generated by Django 5.0.2 on 2024-03-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='quantidade_disponivel',
            field=models.IntegerField(default=0),
        ),
    ]
