# Generated by Django 5.0.3 on 2024-03-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_agendamento_nova_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='data_original',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='hora_original',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='nova_hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
