# Generated by Django 5.0.2 on 2024-03-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_equipamento_quantidade_disponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('agendado', 'Agendado'), ('cancelado', 'Cancelado')], default='disponivel', max_length=20),
        ),
    ]
