# Generated by Django 5.0.2 on 2024-03-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_equipamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='reagendado',
            field=models.BooleanField(default=False),
        ),
    ]
