# Generated by Django 5.0.3 on 2024-03-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_agendamento_data_original_agendamento_hora_original_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='data_aquisicao',
            field=models.DateField(),
        ),
    ]
