# Generated by Django 5.0.2 on 2024-03-12 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0005_agendamento_reagendado'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='tipo_servico',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
