# Generated by Django 5.0.3 on 2024-03-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0005_alter_equipamento_data_aquisicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='data_emprestimo',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
