# Generated by Django 5.0.3 on 2024-03-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0006_agendamento_data_emprestimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='prazo_restante',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='situacao',
            field=models.CharField(default='Agendado', max_length=100),
        ),
    ]
