# Generated by Django 5.0.3 on 2024-03-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0007_agendamento_prazo_restante_agendamento_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='emprestado',
            field=models.BooleanField(default=False),
        ),
    ]
