# Generated by Django 5.0.3 on 2024-03-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0008_agendamento_emprestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
