# Generated by Django 5.0.3 on 2024-03-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0009_agendamento_data_devolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='devolvido',
            field=models.BooleanField(default=False),
        ),
    ]
