# Generated by Django 5.0.3 on 2024-03-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0010_agendamento_devolvido'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='quantidade_dias',
            field=models.IntegerField(choices=[(1, '1 dia'), (2, '2 dias'), (3, '3 dias')], default=3),
        ),
    ]
